#! /bin/sh

sxhkd &
wmname LG3D
xrdb -merge ~/.Xresources
compton --config /dev/null -i 0.9 --inactive-dim 0.2 -b
monitorFix.sh
nitrogen --restore &

enforce_monitor_position.sh eDP-1-1 '^3' &
enforce_monitor_position.sh DP-1-1 '^1' &

bspc monitor DP-1-1 -d I II III
bspc monitor HDMI-0 -d  IV V VI VII VIII
bspc monitor eDP-1-1 -d IX X 

bspc config border_width         0
bspc config window_gap          18

bspc rule -a steam desktop=^1

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a steam state=floating
